### ISSUE TITLE
RuntimeWarning when calling densCols with arrays with length one

### ISSUE THREAD

**Issue by ctberthiaume** [AlexanderButyaev/kern_smooth#2]
When passing x and y with length one to `densCols` I get the following error message (I'm not sure if the second one refers to the same problem).

```
/AAA/lib/python3.8/site-packages/kern_smooth/ks.py:48: RuntimeWarning: invalid value encountered in true_divide
  cols[select] = colpal / (len(dens) - 1.) if len(dens) > 0 else colpal
<__array_function__ internals>:5: UserWarning: Warning: converting a masked element to nan.
/AAA/lib/python3.8/site-packages/numpy/core/_asarray.py:85: UserWarning: Warning: converting a masked element to nan.
  return array(a, dtype, copy=False, order=order)
```

I didn't trace values through the function, but I wonder if `len(dens) - 1.` evaluates to 0 in these cases leading to division by zero.

https://github.com/AlexanderButyaev/kern_smooth/blob/bcf0b6dea616b920102c25db35f7d45870b416a6/kern_smooth/ks.py#L48

I'm using kern-smooth version 1.0.12 and numpy version 1.18.2.

**Comment by AlexanderButyaev** [comment]
Makes sense. Indeed that's the problem. I would argue that array of the length 1 or less would not make a lot of sense but as a corner case - I admit - it was not there.

Fixed in commit [# 8903fa278f0f0f72fce57ac0cc8bf5901f3e0e89](https://github.com/AlexanderButyaev/kern_smooth/commit/8903fa278f0f0f72fce57ac0cc8bf5901f3e0e89) and released next version on pypi: kern-smooth-1.0.13

Thanks!
